FROM python:3.11 AS requirements

RUN python3 -m pip install mypy[mypyc] pytest system-helpers>=0.0.3 typeguard

RUN apt-helpers install-packages --update --clean --packages git docker.io

FROM requirements AS compile-hwloc

ARG HWLOC_VERSION

RUN <<EOF
    set -ex

    apt-helpers install-packages --update --clean --packages libtool autoconf automake pkg-config

    git clone --depth=1 --branch=hwloc-${HWLOC_VERSION} https://github.com/open-mpi/hwloc /opt/open-mpi/hwloc-sources

    cd /opt/open-mpi/hwloc-sources

    ./autogen.sh

    mkdir build && cd build

    ../configure --prefix=/opt/hwloc-${HWLOC_VERSION} --enable-shared

    make -j8 install
EOF

FROM requirements AS final

ARG HWLOC_VERSION

COPY --from=compile-hwloc /opt/hwloc-${HWLOC_VERSION} /opt/hwloc-${HWLOC_VERSION}

ENV PATH=/opt/hwloc-${HWLOC_VERSION}/bin:$PATH
