on:
    workflow_call:
        outputs:
            CI_IMAGE:
                value: ${{ jobs.set-vars.outputs.CI_IMAGE }}
            CI_REGISTRY:
                value: ${{ jobs.set-vars.outputs.CI_REGISTRY }}

env:
    REGISTRY: ghcr.io

jobs:

    set-vars:
        runs-on: [ubuntu-latest]
        outputs:
            CI_IMAGE   : ${{ steps.common.outputs.CI_IMAGE }}
            CI_REGISTRY: ${{ steps.common.outputs.CI_REGISTRY }}
        steps:
            - name: Export common variables.
              id  : common
              run : |
                  echo "CI_IMAGE=${{ env.REGISTRY }}/${{ github.repository }}" >> $GITHUB_OUTPUT
                  echo "CI_REGISTRY=${{ env.REGISTRY }}"                       >> $GITHUB_OUTPUT
